/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.39
 * Generated at: 2020-02-12 07:48:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.home.en.general.whoweare.korea;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class korea_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/jsp/common/import/taglib.jspf", Long.valueOf(1555304080000L));
    _jspx_dependants.put("jar:file:/home/ktbnetwork/www/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/home/ktbnetwork/www/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1528432326000L));
    _jspx_dependants.put("jar:file:/home/ktbnetwork/www/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<section id=\"container\" class=\"container\">\r\n");
      out.write("\t\t\t<nav class=\"nav\">\r\n");
      out.write("\t\t\t\t<ol class=\"navArea\"><li>HOME</li><li>WHO WE ARE</li></ol>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t<div class=\"visualArea\">\r\n");
      out.write("\t\t\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t\t\t<h1 class=\"pageTit\">Who We Are</h1>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"pageTxt\">Our team works with you to ensure successful investments.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"tabArea\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"pageTab\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"sub on\"><a href=\"/home/en/whoweare/korea.do\" aria-selected=\"true\">KOREA</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"subTab\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"on\"><a href=\"#\" aria-selected=\"true\">Investment</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Management</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"sub\"><a href=\"/home/en/whoweare/china.do\">CHINA</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"subTab\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"on\"><a href=\"#\" aria-selected=\"true\">Investment</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Management</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Investment -->\r\n");
      out.write("\t\t\t\t<div class=\"inner tabCont on\"><!-- 탭 활성화시 class=\"on\" -->\r\n");
      out.write("\t\t\t\t\t<h2 class=\"hidden\">KOREA Investment</h2><!-- 탭 타이틀 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"memberList\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"active\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team01.jpg\" alt=\"Shin Jin Ho\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>Shin Jin Ho <span class=\"pointColor\">KOREA / CEO</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dd>Seoul National University (Chemical Engineering)<br>Seoul National University, Graduate School of Chemistry<br>Hyundai Electronics Co., Ltd<br>KTB Network</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team01_on.jpg\" alt=\"Shin Jin Ho\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t활성화시 이미지, hover시 이미지\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"/static/home/en/images/contents/thumb_team01_off.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Shin Jin Ho</strong> CEO\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team02.jpg\" alt=\"Kim Chang Kyu\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>Kim Chang Kyu <span class=\"pointColor\">KOREA / Investment / Vice President</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dd>Yonsei University (Economics)<br>Yonsei Graduate School of Economics<br>Dong Nam Lease<br>KTB Network</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team02_off.jpg\" alt=\"Kim Chang Kyu\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Kim Chang Kyu</strong> Vice President\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team03.jpg\" alt=\"Lee Seung Ho\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>Lee Seung Ho <span class=\"pointColor\">KOREA / Investment / Executive Managing Director</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dd>Yonsei University (History)<br>S.N.21<br>Dacom<br>KTB Network</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team03_off.jpg\" alt=\"Lee Seung Ho\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Lee Seung Ho</strong> Executive Managing Director\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team04.jpg\" alt=\"Lim Dong Hyeon\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>Lim Dong Hyeon <span class=\"pointColor\">KOREA / Investment / Executive Managing Director</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dd>Korea University (Business)<br>Korea University, Graduate School of Business<br>Suwon University, PhD in Business Administration<br>Nara Banking Corporation<br>KTB Network</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team04_off.jpg\" alt=\"Lim Dong Hyeon\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Lim Dong Hyeon</strong> Executive Managing Director\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team05.jpg\" alt=\"Park Seon Bae\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>Park Seon Bae <span class=\"pointColor\">KOREA / Investment / Executive Managing Director</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dd>Seoul National University (Chemical Engineering)<br>Seoul National University, Graduate School of Chemistry<br>Ssang Yong Oil<br>KTB Network</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team05_off.jpg\" alt=\"Park Seon Bae\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Park Seon Bae</strong> Executive Managing Director\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team06.jpg\" alt=\"Shin Tae Kwang\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>Shin Tae Kwang <span class=\"pointColor\">KOREA / Investment / Managing Director</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dd>Sung Kyun Kwan University<br>(Mechanical Design and Production Engineering)<br>KTB Network</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team06_off.jpg\" alt=\"Shin Tae Kwang\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Shin Tae Kwang</strong> Managing Director\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team07.jpg\" alt=\"Kim Jae Han\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>Kim Jae Han <span class=\"pointColor\">KOREA / Investment / Managing Director</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dd>Sogang University (Sociology)<br>KTB Network</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team07_off.jpg\" alt=\"Kim Jae Han\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Kim Jae Han</strong> Managing Director\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team08.jpg\" alt=\"Kim Eun Sook\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>Kim Eun Sook <span class=\"pointColor\">KOREA / Investment / Director</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dd>Samsung C&amp;T<br>KangJeGyu Film<br>KTB Network</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team08_off.jpg\" alt=\"Kim Eun Sook\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Kim Eun Sook</strong> Director\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team10.jpg\" alt=\"Kyung Kuk Hyun\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>Kyung Kuk Hyun <span class=\"pointColor\">KOREA / Investment / Director</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dd>Seoul National University<br>(Naval Architecture &amp; Ocean Engineering)<br>SK C&amp;C<br>KTB Network</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team10_off.jpg\" alt=\"Kyung Kuk Hyun\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Kyung Kuk Hyun</strong> Director\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team11.jpg\" alt=\"Jang Sung Yeop\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>Jang Sung Yeop <span class=\"pointColor\">KOREA / Investment / Director</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dd>Seoul National University (Law)<br>Forward Ventures(Coupang)<br>NHN Corporation</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team11_off.jpg\" alt=\"Jang Sung Yeop\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Jang Sung Yeop</strong> Director\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team12.jpg\" alt=\"Chun Ji Woong\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>Chun Ji Woong <span class=\"pointColor\">KOREA / Investment / Director</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dd>Seoul National University, Graduate School of Pharmacy<br>Chong Kun Dang<br>Daiichi Sankyo (Clinical Development)<br>KTB Network</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team12_off.jpg\" alt=\"Chun Ji Woong\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Chun Ji Woong</strong> Director\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team36.jpg\" alt=\"Seong Kyeong A\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>Seong Kyeong A <span class=\"pointColor\">KOREA / Investment / Team Manager</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dd><dd>KAIST Ph.D. (Chemical and Biomolecular Engineering)<br>LG Chem, Ltd.<br>KIBO (Korea Technology Finance Corporation)</dd></dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team36_off.jpg\" alt=\"Seong Kyeong A\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Seong Kyeong A</strong> Team Manager\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team13.jpg\" alt=\"Jeun Kyung Mi\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>Jeun Kyung Mi <span class=\"pointColor\">KOREA / Investment / Team Manager</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dd>CJ E&M</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team13_off.jpg\" alt=\"Jeun Kyung Mi\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Jeun Kyung Mi</strong> Team Manager\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team39.jpg\" alt=\"Heo Jongsoo\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>Heo Jongsoo <span class=\"pointColor\">Korea / Investment / Team Manager</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dd>KAIST (Electrical Engineering)</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dd>Hyundai Motor Company</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team39_off.jpg\" alt=\"Heo Jongsoo\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Heo Jongsoo</strong> Team Manager\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team18.jpg\" alt=\"Cha Seung Jun\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>Cha Seung Jun <span class=\"pointColor\">KOREA / Investment  / Team Manager</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd>KAIST (Mechanical engineering)<br>Lawschool, Chung Ang University</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt>Responsibilities</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd>Deal Sourcing &amp; Deal Diligence</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team18_off.jpg\" alt=\"Cha Seung Jun\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>Cha Seung Jun</strong> Team Manager\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team40.jpg\" alt=\"Kim Beomjun\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>Kim Beomjun <span class=\"pointColor\">Korea / Investment / Senior Associate</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dd>Korea university division of biotechnology</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dd>Samjong KPMG Audit / Deal advisory</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dd>KIBO</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team40_off.jpg\" alt=\"Kim Beomjun\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Kim Beomjun</strong> Senior Associate\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team14.jpg\" alt=\"Kim Hye Sung\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>Kim Hye Sung <span class=\"pointColor\">KOREA / Investment / Senior Associate</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dd>University of Chicago (Economics)<br>Freenters Co-founder&amp;CEO<br>Sparklabs<br>EarlierCare Co-founder&amp;CSO</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dt>Responsibilities</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dd>Deal Sourcing&amp;Deal Diligence</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team14_off.jpg\" alt=\"Kim Hye Sung\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Kim Hye Sung</strong> Senior Associate\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team15.jpg\" alt=\"Kim Man Sik\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>Kim Man Sik <span class=\"pointColor\">KOREA / Investment / Senior Associate</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dd>Seoul National University (Pharmacy)<br>Korea Eisai</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dt>Responsibilities</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dd>Deal Sourcing&amp;Deal Diligence</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team15_off.jpg\" alt=\"Kim Man Sik\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Kim Man Sik</strong> Senior Associate\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- //Investment -->\r\n");
      out.write("\t\t\t\t<!-- Management -->\r\n");
      out.write("\t\t\t\t<div class=\"inner tabCont\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"hidden\">KOREA Management</h2><!-- 탭 타이틀 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"memberList\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"memberWrap\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"memberInner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3 class=\"title\">CEO</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"active\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team01.jpg\" alt=\"Shin Jin Ho\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h3>Shin Jin Ho <span class=\"pointColor\">KOREA / CEO</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<dd>Seoul National University (Chemical Engineering)<br>Seoul National University, Graduate School of Chemistry<br>Hyundai Electronics Co., Ltd<br>KTB Network</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team01_on.jpg\" alt=\"Shin Jin Ho\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!--\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t활성화시 이미지, hover시 이미지\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"/static/home/en/images/contents/thumb_team01_off.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong>Shin Jin Ho</strong> CEO\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"memberInner\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"title\">Compliance</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team17.jpg\" alt=\"Kum Kyunghwan\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>Kum Kyung Hwan <span class=\"pointColor\">KOREA / Management / Team Manager</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd>Seoul National University (Dept. of Private Law)<br>NHN Entertainment Corp.</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt>Responsibilities</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd>Law-abiding monitor</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team17_off.jpg\" alt=\"Kum Kyunghwan\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>Kum Kyung Hwan</strong> Team Manager\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"memberInner\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"title\">Management</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team19.jpg\" alt=\"Chung Do\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>Chung Do <span class=\"pointColor\">KOREA / Management / Senior Managing Director</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd>Seoul National University (International Economics)<br>Daewoo<br>KTB Network</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt>Responsibilities</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd>Management support</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team19_off.jpg\" alt=\"Chung Do\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>Chung Do</strong> Senior Managing Director\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team08.jpg\" alt=\"Kim Eun Sook\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>Kim Eun Sook <span class=\"pointColor\">KOREA / Management / Director</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd>Samsung C&amp;T<br>KangJeGyu Film<br>KTB Network</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt>Responsibilities</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd>Human resource management</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team08_off.jpg\" alt=\"Kim Eun Sook\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>Kim Eun Sook</strong> Director\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team22.jpg\" alt=\"Hwang Moon Chul\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>Hwang Moon Chul <span class=\"pointColor\">KOREA / Management  / Director</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd>Samil PwC Assurance/Deal<br>HM consulting Inc<br>KTB Investment &amp; Securities</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt>Responsibilities</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd>Management planning and Accounting</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team22_off.jpg\" alt=\"Hwang Moon Chul\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>Hwang Moon Chul</strong> Director\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team23.jpg\" alt=\"Lee Ji Hyun\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>Lee Ji Hyun <span class=\"pointColor\">KOREA / Management / Team Manager</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd>K Cube Ventures<br>KTB Network</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt>Responsibilities</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd>Treasury/public disclosure</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team23_off.jpg\" alt=\"Lee Ji Hyun\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>Lee Ji Hyun</strong> Team Manager\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team24.jpg\" alt=\"Hong Ji Won\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>Hong Ji Won <span class=\"pointColor\">KOREA / Management / Team Manager</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd>Hang Yang University (Business)<br>Kyung Nong<br>Inter M</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt>Responsibilities</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd>Fund planning and Fund management</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team24_off.jpg\" alt=\"Hong Ji Won\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>Hong Ji Won</strong> Team Manager\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team25.jpg\" alt=\"Ko Eun Bi\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>Ko Eun Bi <span class=\"pointColor\">KOREA / Management / Team Manager</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd>HQ Investment</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt>Responsibilities</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd>Fund planning and investment management </dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team25_off.jpg\" alt=\"Ko Eun Bi\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>Ko Eun Bi</strong> Team Manager\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team26.jpg\" alt=\"Lee Sin Heer\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>Lee Sin Hee <span class=\"pointColor\">KOREA / Management / Manager</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd>KTB Network</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt>Responsibilities</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd>Accounting</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team26_off.jpg\" alt=\"Lee Sin Heer\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>Lee Sin Hee</strong> Manager\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team27.jpg\" alt=\"Jung Ga Young\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>Jung Ga Young <span class=\"pointColor\">KOREA / Management / Manager</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd>Etners</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt>Responsibilities</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd>Fund management</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team27_off.jpg\" alt=\"Jung Ga Young\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>Jung Ga Young</strong> Manager\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team37.jpg\" alt=\"Cho Eun Sol\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>Cho Eun Sol <span class=\"pointColor\">KOREA / Management / Associate</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd>Etners</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt>Responsibilities</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd>Investment management</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team37_off.jpg\" alt=\"Cho Eun Sol\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>Cho Eun Sol</strong> Associate\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"memberInner\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"title\">BI Center</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team04.jpg\" alt=\"Lim Dong Hyeon\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>Lim Dong Hyeon <span class=\"pointColor\">KOREA / Investment / Executive Managing Director</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd>Korea University (Business)<br>Korea University, Graduate School of Business<br>Nara Banking Corporation<br>KTB Network</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team04_off.jpg\" alt=\"Lim Dong Hyeon\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>Lim Dong Hyeon</strong> Executive Managing Director\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"left\"><img src=\"/static/home/en/images/contents/img_team29.jpg\" alt=\"Lee Ji Eun\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>Lee Ji Eun <span class=\"pointColor\">KOREA / Management BI center / Senior Associate</span></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt>Career</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd>Dong Seoul University BI Center</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt>Responsibilities</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd>BI Center Manager</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"img\"><img src=\"/static/home/en/images/contents/thumb_team29_off.jpg\" alt=\"Lee Ji Eun\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>Lee Ji Eun</strong> Senior Associate\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- //Management -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
