/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.39
 * Generated at: 2019-05-09 01:01:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.mobile.en.general.meetourpartners.overseas;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class overseas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/jsp/common/import/taglib.jspf", Long.valueOf(1555304080000L));
    _jspx_dependants.put("jar:file:/home/ktbnetwork/www/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/home/ktbnetwork/www/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1528432326000L));
    _jspx_dependants.put("jar:file:/home/ktbnetwork/www/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"container\">\r\n");
      out.write("\t\t<div class=\"contents\">\r\n");
      out.write("\t\t\t<div class=\"visualArea\">\r\n");
      out.write("\t\t\t\t<h1 class=\"pageTit\">Meet Our Partners</h1>\r\n");
      out.write("\t\t\t\t<p role=\"text\" class=\"pageTxt\">We will be your most realiable partner in investment.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"partner\">\r\n");
      out.write("\t\t\t\t<div class=\"tabType1\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/home/en/meetourpartners/all.do\">ALL</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/home/en/meetourpartners/domestic.do\">DOMESTIC</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"on\"><a href=\"/home/en/meetourpartners/overseas.do\" aria-selected=\"true\">OVERSEAS</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"tabCont\"  style=\"display:block\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"hidden\">OVERSEAS</h2>\r\n");
      out.write("\t\t\t\t\t<ul class=\"partnerList\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop32\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_32.gif\" alt=\"B2LINK image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>B2LINK</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop33\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_33.gif\" alt=\"한국엔에프씨 image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>BRAVOWHALE TECHNOLOGY</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop34\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_34.gif\" alt=\"B2LINK image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>CHINA CORD BLOOD</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop35\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_35.gif\" alt=\"CORENTEC image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>CORENTEC</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop39\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_39.gif\" alt=\"HOLMES HOLDING CO.LTD. image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>HOLMES HOLDING CO.LTD.</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop41\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_41.gif\" alt=\"IZENE TECH INC. image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>IZENE TECH INC.</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop43\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_43.gif\" alt=\"LOHO HOLDINGS INC. image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>LOHO HOLDINGS INC.</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop44\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_44.gif\" alt=\"MINDRAY MEDICAL image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>MINDRAY MEDICAL</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop47\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_47.gif\" alt=\"UTAN image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>UTAN</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop48\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_48.gif\" alt=\"VERSILICON HOLDINGS image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>VERISILICON HOLDINGS</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop55\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_55.gif\" alt=\"CARSGEN image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>CARSGEN</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop61\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_61.gif\" alt=\"FOCUS MEDIA image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>FOCUS MEDIA</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop72\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_72.gif\" alt=\"ORIG3N image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>ORIG3N</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop73\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_73.gif\" alt=\"ORTHOSENSOR image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>ORTHOSENSOR</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop77\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_77.gif\" alt=\"QEEXO image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>QEEXO</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop80\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_80.gif\" alt=\"SMI image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>SMI</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop81\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_81.gif\" alt=\"TAL EDUCATION GROUP image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>TAL EDUCATION GROUP</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop83\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_83.gif\" alt=\"TUDOU image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>TUDOU</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop87\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_87.gif\" alt=\"XW Labs image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>XW LABS</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop88\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_88.gif\" alt=\"Aprinoia image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>APRINOIA</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop89\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_90.gif\" alt=\"KINOVA image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>KINOVA</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop90\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_89.gif\" alt=\"Berkeleylights image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>BERKELEYLIGHTS</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop92\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_92.gif\" alt=\"Neuroptika image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>NEUROPTIKA</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- 0503 추가 -->\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop100\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_100.gif\" alt=\"Grab image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>Grab</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop101\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_101.gif\" alt=\"Nobroker image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>Nobroker</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop102\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/en/images/contents/img_partners_102.gif\" alt=\"Missfresh image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>Missfresh</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<!-- //0503 추가 -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul><!-- //partnerList -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div><!-- //contents -->\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("<!-- partner layerpop(L) -->\r\n");
      out.write("\t<!-- B2LINK -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop32\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">B2LINK</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_32.gif\" alt=\"B2LINK image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.b2link.co.kr\" target=\"_blank\" title=\"open new window\">http://www.b2link.co.kr</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tB2LiNK is a global e-commerce company, distributing domestic beauty and fashion commodities through e-commerce channels throughout China and Southeast Asia. It also operates its independent mobile commerce for Chinese customers and realizes innovation of distribution channels through its Big Data business.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //B2LINK -->\r\n");
      out.write("\t<!-- BRAVOWHALE TECHNOLOGY -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop33\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">BRAVOWHALE TECHNOLOGY</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_33.gif\" alt=\"BRAVOWHALE TECHNOLOGY image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.bravowhale.com\" target=\"_blank\" title=\"open new window\">http://www.bravowhale.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tBravo Whale Technology is a system software development company founded in 2014. It provides asset-managing companies with customized management system software based on its Cloud and mobile platforms. Bravo Whale Technology has established its offices in Beijing and Shanghai as well as an R&D center in Kunshan. \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //BRAVOWHALE TECHNOLOGY -->\r\n");
      out.write("\t<!-- CHINA CORD BLOOD -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop34\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">CHINA CORD BLOOD</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_34.gif\" alt=\"CHINA CORD BLOOD image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.chinacordbloodcorp.com\" target=\"_blank\" title=\"open new window\">http://www.chinacordbloodcorp.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tChina Cord Blood(CCBC)is a life sciences enterprise dedicated to the storage of unbilical cord blood stem cells, leveraging the rapid developments in life sciences research and the increasing popularity and rapid advancement of clinical applications using stem cells\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //CHINA CORD BLOOD -->\r\n");
      out.write("\t<!-- CORENTEC -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop35\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">CORENTEC</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_35.gif\" alt=\"CORENTEC image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.corentec.com\" target=\"_blank\" title=\"open new window\">http://www.corentec.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tCorentec's Central Technology Institute was established in order for the patients to have an improved quality of life through the development of advanced medical devices and surgical techniques.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //CORENTEC -->\r\n");
      out.write("\t<!-- HOLMES HOLDING CO.LTD. -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop39\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">HOLMES HOLDING CO.LTD.</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_39.gif\" alt=\"HOLMES HOLDING CO.LTD. image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.mogoroom.com\" target=\"_blank\" title=\"open new window\">http://www.mogoroom.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tHolmes Holding Co., Ltd(Mogo Room)established in December 2013, it has developed to be China’s leading shared apartment company, providing high quality room for white-collar’s long-term renting demand. \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //HOLMES HOLDING CO.LTD. -->\r\n");
      out.write("\t<!-- IZENE TECH INC. -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop41\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">IZENE TECH INC.</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_41.gif\" alt=\"IZENE TECH INC. image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.b5m.com\" target=\"_blank\" title=\"open new window\">http://www.b5m.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tB5M provides a one-stop shopping platform and free delivery service for entire-network shopping and helps users buy quality goods in the most economical way. \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //IZENE TECH INC. -->\r\n");
      out.write("\t<!-- LOHO HOLDINGS INC. -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop43\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">LOHO HOLDINGS INC.</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_43.gif\" alt=\"LOHO HOLDINGS INC. image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.loho88.cn\" target=\"_blank\" title=\"open new window\">http://www.loho88.cn</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tLOHO is a company specialized in design, production, sales and service of glasses. All over China, LOHO sells items both on and offline at stores located nationwide.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //LOHO HOLDINGS INC. -->\r\n");
      out.write("\t<!-- MINDRAY MEDICAL -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop44\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">MINDRAY MEDICAL</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_44.gif\" alt=\"LOHO HOLDINGS INC. image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.mindray.com\" target=\"_blank\" title=\"open new window\">http://www.mindray.com </a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tMindray Medical is a world-class medical H/W and S/W provider that was founded in Shenzhen, China, in 1991. It owns 41 subsidiaries in 31 countries, forming a global network for R&D, sales and services.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //MINDRAY MEDICAL -->\r\n");
      out.write("\t<!-- UTAN -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop47\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">UTAN</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_47.gif\" alt=\"UTAN image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.yurongcorp.com\" target=\"_blank\" title=\"open new window\">http://www.yurongcorp.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tUtan provides social media &amp; E-commerce services exclusive for women. It has secured more than 60 million users through 5 applications including V-Line Fitness, Girl's Alliance, etc.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //UTAN -->\r\n");
      out.write("\t<!-- VERSILICON HOLDINGS -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop48\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">VERISILICON HOLDINGS</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_48.gif\" alt=\"VERSILICON HOLDINGS image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.verisilicon.com\" target=\"_blank\" title=\"open new window\">http://www.verisilicon.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tVeriSilicon Holdings Co., Ltd. is a Silicon Platform as a Service (SiPaaS™) company that provides IP-centric, platform based custom silicon solutions and end-to-end semiconductor turnkey services for a wide range of applications across a wide variety of end markets including mobile internet devices, datacenters, the Internet of Things (IoT), wearable electronics, smart homes, and automotive. \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //VERSILICON HOLDINGS -->\r\n");
      out.write("\t<!-- CARSGEN -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop55\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">CARSGEN</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_55.gif\" alt=\"CARSGEN image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.carsgen.com \" target=\"_blank\" title=\"open new window\">http://www.carsgen.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tCARsgen Therapeutics has developed CAR-T, which is an innovative immune anti-cancer agent in pursuit of developing obstinate cancer treatments. CARsgen is developing First-in-Class solid cancer treatment CAR-T on a global scale including China, taking the lead of mankind’s effort to overcome cancer.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //CARSGEN -->\r\n");
      out.write("\t<!-- FOCUS MEDIA -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop61\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">FOCUS MEDIA<em>NASDAQ</em></h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit type02\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_61.gif\" alt=\"FOCUS MEDIA image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.focusmedia.cn\" target=\"_blank\" title=\"open new window\">http://www.focusmedia.cn</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tFOCUS MEDIA is China's largest outdoor advertisement company that is renowned for its elevator LCD advertisements. In 2005, it was listed successfully on NASDAQ, becoming a myth in the Chinese media industry.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //FOCUS MEDIA -->\r\n");
      out.write("\t<!-- ORIG3N -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop72\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">ORIG3N</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_72.gif\" alt=\"ORIG3N image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.orig3n.com\" target=\"_blank\" title=\"open new window\">http://www.orig3n.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tORIG3N provides iPS banking service and iPS-based cell experiment models in utilization of its iPS (induced pluripotent stem cells) technology which was a Nobel prize winner in 2012. ORIG3N has secured the largest amount of human iPS samples in the form of crowdsourcing around the globe. By making rare disease iPS samples, it also helps developing new medicines for rare diseases. \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //ORIG3N -->\r\n");
      out.write("\t<!-- ORTHOSENSOR -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop73\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">ORTHOSENSOR</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_73.gif\" alt=\"ORTHOSENSOR image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.orthosensor.com\" target=\"_blank\" title=\"open new window\">http://www.orthosensor.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tOrthosensor develops products for smart artificial joint implants. The pressure for the optimal status of artificial joints in the body is quantified by means of Orthosensor’s smart sensors during the artificial joint implant, which minimizes reoperations and aftereffects. In addition, it has developed implant sensors for real-time monitoring after an operation. With its accumulated data, Orthosensor seeks to improve the quality of patients’ life after artificial joint implants.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //ORTHOSENSOR -->\r\n");
      out.write("\t<!-- QEEXO -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop77\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">QEEXO</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_77.gif\" alt=\"QEEXO image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.qeexo.com\" target=\"_blank\" title=\"open new window\">http://www.qeexo.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tQeexo provides an innovative UI platform that interacts between users and mobile/touch devices based on the HCI (human and computer interaction) and machine learning technology. \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //QEEXO -->\r\n");
      out.write("\t<!-- SMI -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop80\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">SMI<em>HKSE</em></h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit type02\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_80.gif\" alt=\"SMI image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.smi198.com\" target=\"_blank\" title=\"open new window\">http://www.smi198.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tSMI Holdings is an entertainment business provider. The major business areas include movie theater service operation, film/TV series production and distribution, advertisement, online shopping mall operation, etc. \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //SMI -->\r\n");
      out.write("\t<!-- TAL EDUCATION GROUP -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop81\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">TAL EDUCATION GROUP<em>NYSE</em></h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit type02\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_81.gif\" alt=\"TAL EDUCATION GROUP image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.100tal.com\" target=\"_blank\" title=\"open new window\">http://www.100tal.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tal Education Group is a Chinese company that provides on/offline education service specifically for middle and high school students. Specific business areas include institute franchising, one-to-one tutoring service, and online education service. \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //TAL EDUCATION GROUP -->\r\n");
      out.write("\t<!-- TUDOU -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop83\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">TUDOU<em>NYSE</em></h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit type02\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_83.gif\" alt=\"TUDOU image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.tudou.com\" target=\"_blank\" title=\"open new window\">http://www.tudou.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tTudou is a Chinese website specialized in online video service. Since 2012 when it was merged with Youku, one of its competitors, Tudou has attracted investment from Alibaba, China's largest online e-commerce company, and it has become China's largest video service platform, being called the ‘YouTube of China.’\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //TUDOU -->\r\n");
      out.write("\t<!-- XW Labs -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop87\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">XW LABS</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_87.gif\" alt=\"XW Labs image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.xwlabs.com\" target=\"_blank\" title=\"open new window\">http://www.xwlabs.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tLocated in Wuhan, China, XW Laboratories is a pharmaceutical company that develops original drugs for Central Nerve System. The XW Labs has received investments from us, the global pharmaceutical Johnson &amp; Johnson, the global CRO WuXi and top-tier investors in Asia Pacific such as KPCB China, WI Harper and Element Capital.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //XW Labs -->\r\n");
      out.write("\t<!-- APRINOIA -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop88\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">APRINOIA</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_88.gif\" alt=\"APRINOIA image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"https://www.aprinoia.com\" target=\"_blank\" title=\"open new window\">https://www.aprinoia.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tAprinoia is a biotechnology company focusing on degenerative brain diseases. The company is developing PET Tracer for a more accurate diagnosis of Alzheimer’s, Parkinson’s and other degenerative diseases as well as treatments (low-molecular weight compound, antibodies)\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //APRINOIA -->\r\n");
      out.write("\t<!-- KINOVA -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop89\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">KINOVA</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_90.gif\" alt=\"KINOVA image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"https://www.kinovarobotics.com/en\" target=\"_blank\" title=\"open new window\">https://www.kinovarobotics.com/en</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tKinova is a global service robot arm manufacturer in Canada. Starting with service robots for supporting the disabled and the elderly, the company is continuing to develop technologies that boast a high degree of freedom in everyday activities.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //KINOVA -->\r\n");
      out.write("\t<!-- BERKELEYLIGHTS -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop90\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">BERKELEYLIGHTS</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_89.gif\" alt=\"BERKELEYLIGHTS image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"https://www.berkeleylights.com\" target=\"_blank\" title=\"open new window\">https://www.berkeleylights.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tBerkeley Lights is a cell research equipment manufacturer specializing in research and pharmaceutical development. Its Opto Eletro Positioning(cell manipulation technology through electromagnetic fields) enable massive cost and time savings in cell separation, cultivation, analysis and extraction. The company is developing products that can be used in various fields such as cell extraction and developments, and antibody development.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //BERKELEYLIGHTS -->\r\n");
      out.write("\t<!-- NEUROPTIKA -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop92\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">NEUROPTIKA</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_92.gif\" alt=\"NEUROPTIKA image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"https://www.neuroptika.com\" target=\"_blank\" title=\"open new window\">https://www.neuroptika.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tdevelopment company. Through regeneration of the optic nerve cells, the company looks to achieve breakthrough treatments in cornea regeneration, improving xerophthalmia following LASIK procedures, glaucoma and other rare optical nerve disease.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //NEUROPTIKA -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 0503 추가 -->\r\n");
      out.write("\t<!-- Grab -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop100\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">Grab</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_100.gif\" alt=\"Grab image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"https://www.grab.com/sg/\" target=\"_blank\" title=\"open new window\">https://www.grab.com/sg/</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tGrab is a ride-hailing platform that offers booking service for taxis, private cars, and motorbikes through one mobile.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //Grab -->\r\n");
      out.write("\t<!-- Nobroker -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop101\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">Nobroker</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_101.gif\" alt=\"Nobroker image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"https://www.nobroker.in/\" target=\"_blank\" title=\"open new window\">https://www.nobroker.in/</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tNoBroker.com is India’s unique real estate platform that makes it possible to Buy/Sell/Rent houses without paying any brokerage.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //Nobroker -->\r\n");
      out.write("\t<!-- Missfresh -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop102\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">Missfresh</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/en/images/contents/img_partners_102.gif\" alt=\"Missfresh image\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"https://www.missfresh.cn/\" target=\"_blank\" title=\"open new window\">https://www.missfresh.cn/</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tMissfresh is one of the leading e-commerce retailer in china. Founded in Nov 2014, by founder Xuzheng(CEO) and co-founder Zengbin(COO). Company sales Fruit, Egg &amp; Meat, Fisheries, Vegetables, Dairy, Beverage, Snacks etc,.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">close</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //Missfresh -->\r\n");
      out.write("<!-- //0503 추가 -->\r\n");
      out.write("\t\r\n");
      out.write("<!-- //partner layerpop(L) -->\r\n");
      out.write("\t<div class=\"dimmed\"></div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
