/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.39
 * Generated at: 2019-04-16 09:22:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.mobile.en.general.contact.contact;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/jsp/common/import/taglib.jspf", Long.valueOf(1555304080000L));
    _jspx_dependants.put("jar:file:/home/ktbnetwork/www/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/home/ktbnetwork/www/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1528432326000L));
    _jspx_dependants.put("jar:file:/home/ktbnetwork/www/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"container\">\r\n");
      out.write("\t\t<div class=\"contents\">\r\n");
      out.write("\t\t\t<div class=\"visualArea\">\r\n");
      out.write("\t\t\t\t<h1 class=\"pageTit\">Contact</h1>\r\n");
      out.write("\t\t\t\t<p role=\"text\" class=\"pageTxt\">Come meet KTB,<br>the financiers of tomorrow.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"contact\">\r\n");
      out.write("\t\t\t\t<ul class=\"tglList\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" role=\"button\">Pangyo</a><!-- 0415 수정 -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tglCont\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"contactArea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"addr\">10FL, USpace 2A dong, 670 Daewangpangyo-ro, Bundag-gu, Seongnam-city, Gyeonggi-do, Korea</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"map\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong class=\"tit\">Tel</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"tel:02-788-8400\" class=\"data tel\">+82 31-628-6400</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong class=\"tit\">E-mail</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"mailto:webmaster@ktbnetwork.com\" class=\"data mail\">webmaster@ktbnetwork.com</a><!-- 0415 수정 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" role=\"button\">Shanghai</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tglCont\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"contactArea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"addr\">2806, L'Avenue, No.99 Xianxia Road, Changning District, Shanghai, China</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"map\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong class=\"tit\">Tel</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"tel:02-788-8400\" class=\"data tel\">+86-21-60671778</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"data fax\">+86-21-60671779</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong class=\"tit\">E-mail</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"mailto:webmaster@ktbnetwork.com\" class=\"data mail\">webmaster@ktbnetwork.com</a><!-- 0415 수정 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" role=\"button\">Palo Alto</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tglCont\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"contactArea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"addr\">1 California Street, Suite 2800 San Francisco, CA 94111</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"map\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong class=\"tit\">Tel</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"tel:1-650-324-4681\" class=\"data tel\">+1-650-324-4681</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong class=\"tit\">E-mail</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"mailto:info@ktbvc.com\" class=\"data mail\">info@ktbvc.com</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<!-- 삭제\t<h2 class=\"titDep2\">SUBMIT YOUR BUSINESS PLAN</h2>\r\n");
      out.write("\t\t\t\t<ul class=\"formArea\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<strong><label for=\"email\">이메일</label></strong>\r\n");
      out.write("\t\t\t\t\t\t<span><input type=\"text\" id=\"email\" placeholder=\"이메일을 입력하세요.\"></span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<strong><label for=\"name\">이름</label></strong>\r\n");
      out.write("\t\t\t\t\t\t<span><input type=\"text\" id=\"name\" placeholder=\"이름을 입력하세요.\"></span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<strong><label for=\"title\">제목</label></strong>\r\n");
      out.write("\t\t\t\t\t\t<span><textarea class=\"textArea\" rows=\"5\" cols=\"35\" placeholder=\"내용을 입력하세요.\"></textarea></span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<strong><label for=\"title\">첨부파일</label></strong>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"btn_file\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"fileName\" placeholder=\"파일을 첨부해주세요.\" disabled=\"disabled\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\">파일삭제</button>\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"ex_filename\">첨부</label> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"file\" id=\"ex_filename\" class=\"fileHidden\"> \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"formBtn\">보내기</button> -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div><!-- //contents -->\r\n");
      out.write("\t</section>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
