/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.39
 * Generated at: 2019-04-15 05:50:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.error.kr;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class error_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 if(((String)request.getAttribute("javax.servlet.forward.request_uri")).toLowerCase().indexOf("/en/") > -1) { 
      out.write('\r');
      out.write('\n');
 if(request.getRequestURL().toString().toLowerCase().startsWith("http://m.ktbnetwork.com") || request.getRequestURL().toString().toLowerCase().startsWith("https://m.ktbnetwork.com")) { 
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no\">\r\n");
      out.write("\t<meta name=\"format-detection\" content=\"telephone=no\">\r\n");
      out.write("\t<title>Not Found Page - Network</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/static/mobile/en/css/m_font.css\"> \r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/static/mobile/en/css/m_common.css\"> \r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/static/mobile/en/css/m_contents.css\"> \r\n");
      out.write("\t<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"/static/mobile/en/images/favicon/favicon128x128.ico\">\r\n");
      out.write("\t<link rel=\"apple-touch-icon\" href=\"/static/mobile/en/images/favicon/favicon192x192.png\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/static/mobile/en/js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/static/mobile/en/js/common.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"layoutB\">\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<button type=\"button\" class=\"prev\" onclick=\"location.href='javascript:history.go(-1)'\">before</button>\r\n");
      out.write("\t\t<h1>KTB Network</h1>\r\n");
      out.write("\t\t<button type=\"button\" class=\"menu\">menu</button>\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"gnb\">\r\n");
      out.write("\t\t<h2 class=\"hidden\">total menu</h2>\r\n");
      out.write("\t\t<div class=\"menuTop\">\r\n");
      out.write("\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t<p class=\"tit\">KTB Network total menu</p>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"goMain\" onclick=\"location.href='/home/en/main/main.do'\">go main</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<ul class=\"etc\">\r\n");
      out.write("\t\t\t\t<li><a href=\"/home/main/main.do\" role=\"button\">KOREAN</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- //menuTop -->\r\n");
      out.write("\t\t<div class=\"totalMenu\">\r\n");
      out.write("\t\t\t<div class=\"depthOver\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/home/en/watwedo/overview.do\">What We Do</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/home/en/whoweare/korea.do\">Who We Are</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/home/en/meetourpartners/all.do\">Meet Our Partners</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/home/en/contact/contact.do\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/home/en/about/about.do\">About KTB Group</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<!--// -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--//depthOver -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--//totalMenu -->\r\n");
      out.write("\t\t<button type=\"button\" class=\"menuClose\">close</button>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- //gnb -->\r\n");
      out.write("\t\r\n");
      out.write("\t<section class=\"container\">\r\n");
      out.write("\t\t<div class=\"contents\">\r\n");
      out.write("\t\t\t<p class=\"errorTxt\">Not Found Page<br>We apologize for the inconvenience.</p>\r\n");
      out.write("\t\t\t<div class=\"btnArea btnFixed\">\r\n");
      out.write("\t\t\t\t<div class=\"btnBtm\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/home/en/main/main.do\" role=\"button\" class=\"btnFloating\">Main</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<ul class=\"fLink\">\r\n");
      out.write("\t\t\t<li><a href=\"/home/en/watwedo/overview.do\" role=\"button\">What We Do</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/home/main/main.do\" role=\"button\" title=\"open new window\">KOREAN</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/home/en/contact/contact.do\" role=\"button\">CONTACT</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<div class=\"familySite\">\r\n");
      out.write("\t\t\t<span class=\"frmSelect\">\r\n");
      out.write("\t\t\t\t<select title=\"Family Site\">\r\n");
      out.write("\t\t\t\t\t<option value=\"https://m.ktb.co.kr/en/CIE/CIE1.jsp\">KTB Investment &amp; Securities</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"http://m.i-ktb.com/static/mobile/html/MA/m_main_eng.html\">KTB Asset Management</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"https://www.ktbst.co.th/index.php?s=p\">KTB ST</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"http://www.ktbpe.co.kr/en/\">KTB PE</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"http://www.ktbcredit.com/\">KTB Credit Service</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"https://www.ktbvc.com/\">KTB Ventures</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t\t<a href=\"#\" role=\"button\" class=\"btnMove\">GO</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<p class=\"copyright\">COPYRIGHT&copy;KTB Network. ALL RIGHTS RESERVED</p>\r\n");
      out.write("\t</footer>  \r\n");
      out.write(" </body>\r\n");
      out.write("</html>\r\n");
 } else { 
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t<title>error - KTB Network</title>\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"/static/home/en/images/favicon/favicon.ico\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/static/home/en/css/p_font.css\"> \r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/static/home/en/css/p_common.css\"> \r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/static/home/en/css/p_contents.css\">\r\n");
      out.write("\t<!--[if lte IE 8]>\r\n");
      out.write("\t<script src=\"/static/home/en/js/html5shiv.min.js\"></script>\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/static/home/en/js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/static/home/en/js/jquery.jscrollpane.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/static/home/en/js/selectbox.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/static/home/en/js/common.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"accessbility\"><a href=\"#container\">Skip to contents</a></div>\r\n");
      out.write("\t<div id=\"wrap\" class=\"wrap\">\r\n");
      out.write("\t\t<header id=\"header\" class=\"header\">\r\n");
      out.write("\t\t\t<div class=\"headArea\"><!-- 열기 open -->\r\n");
      out.write("\t\t\t\t<h1 class=\"logo\"><a href=\"/home/en/main/main.do\">KTB Network</a></h1>\r\n");
      out.write("\t\t\t\t<a href=\"/home/main/main.do\" class=\"engBtn\">KOR</a>\r\n");
      out.write("\t\t\t\t<div class=\"allMenu\">\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<ul class=\"inner\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/home/en/watwedo/overview.do\">What We Do</a></li><!-- a클릭 시 class=\"on\" 추가 -->\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/home/en/whoweare/korea.do\">Who We Are</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/home/en/meetourpartners/all.do\">Meet Our Partners</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/home/en/contact/contact.do\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/home/en/about/about.do\">About KTB Group</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<section id=\"container\" class=\"container\">\t\t\t\r\n");
      out.write("\t\t\t<article class=\"content\">\r\n");
      out.write("\t\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t\t<div class=\"errorPage\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"errorTxt\">Not Found Page<span class=\"sTxt\">We apologize for the inconvenience.</span></p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/home/en/main/main.do\" role=\"button\" class=\"btnXL action\">Main</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</article>\t\t\t\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<footer id=\"footer\" class=\"footer\">\r\n");
      out.write("\t\t\t<div class=\"footArea\">\r\n");
      out.write("\t\t\t\t<div class=\"policyList\">\r\n");
      out.write("\t\t\t\t\t<address>\r\n");
      out.write("\t\t\t\t\t\t<span>TEL 02-788-8400</span>\r\n");
      out.write("\t\t\t\t\t\t<span>FAX 02-788-8597</span>\r\n");
      out.write("\t\t\t\t\t\t<span>E-MAIL <a href=\"mailto:webmaster@ktbnetwork.com\">webmaster@ktbnetwork.com</a></span><br>\r\n");
      out.write("\t\t\t\t\t\t<span>Seoul 10FL, USpace 2A dong, 670 Daewangpangyo-ro, Bundag-gu, Seongnam-city, Gyeonggi-do, Korea</span>\r\n");
      out.write("\t\t\t\t\t</address>\r\n");
      out.write("\t\t\t\t\t<p class=\"copyRight\">Copyright &copy; KTB Network. All Right Reserved.</p>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"familySite\">\r\n");
      out.write("\t\t\t\t\t<span class=\"frmSelect\">\r\n");
      out.write("\t\t\t\t\t\t<select title=\"Family Site\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"https://www.ktb.co.kr/company/eng/index.jsp\">KTB Investment &amp; Securities</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"http://www.i-ktb.com/static/pc/html/MA/MAE1.html\">KTB Asset Management</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"https://www.ktbst.co.th/index.php?s=p\">KTB ST</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"http://www.ktbpe.co.kr/en/\">KTB PE</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"http://www.ktbcredit.com/\">KTB Credit Service </option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"http://www.ktbvc.com/\">KTB Ventures</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</span>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"logo\"><img src=\"/static/home/en/images/common/logo_footer.png\" alt=\"KTB Network\"></div>\r\n");
      out.write("\t\t\t</div>\t\t\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
 } 
      out.write('\r');
      out.write('\n');
 } else { 
      out.write('\r');
      out.write('\n');
 if(request.getRequestURL().toString().toLowerCase().startsWith("http://m.ktbnetwork.com") || request.getRequestURL().toString().toLowerCase().startsWith("https://m.ktbnetwork.com")) { 
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no\">\r\n");
      out.write("\t<meta name=\"format-detection\" content=\"telephone=no\">\r\n");
      out.write("\t<title>페이지를 찾을 수 없습니다. - KTB 네트워크</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/static/mobile/kr/css/m_font.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/static/mobile/kr/css/m_common.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/static/mobile/kr/css/m_contents.css\">\r\n");
      out.write("\t<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"/static/mobile/kr/images/favicon/favicon128x128.ico\">\r\n");
      out.write("\t<link rel=\"apple-touch-icon\" href=\"/static/mobile/kr/images/favicon/favicon192x192.png\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/static/mobile/kr/js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/static/mobile/kr/js/common.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"layoutB\">\r\n");
      out.write("\t<header>\r\n");
      out.write("\t<button type=\"button\" class=\"prev\" onclick=\"location.href='javascript:history.go(-1)'\">이전</button>\r\n");
      out.write("\t\t<h1><a href=\"/home/main/main.do\">KTB 네트워크</a></h1>\r\n");
      out.write("\t\t<button type=\"button\" class=\"menu\">메뉴</button>\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"gnb\">\r\n");
      out.write("\t\t<h2 class=\"hidden\">전체 메뉴</h2>\r\n");
      out.write("\t\t<div class=\"menuTop\">\r\n");
      out.write("\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t<p class=\"tit\">KTB네트워크 전체메뉴</p>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"goMain\" onclick=\"location.href='/home/main/main.do'\">메인으로</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<ul class=\"etc\">\r\n");
      out.write("\t\t\t\t<li><a href=\"/home/en/main/main.do\" role=\"button\">ENGLISH</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- //menuTop -->\r\n");
      out.write("\t\t<div class=\"totalMenu\">\r\n");
      out.write("\t\t\t<div class=\"depthOver\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/home/watwedo/overview.do\">What We Do</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/home/whoweare/korea.do\">Who We Are</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/home/meetourpartners/all.do\">Meet Our Partners</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/home/news/news/list.do\">News</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/home/contact/contact.do\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/home/about/about.do\">About KTB Group</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<!--// -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--//depthOver -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--//totalMenu -->\r\n");
      out.write("\t\t<button type=\"button\" class=\"menuClose\">닫기</button>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- //gnb -->\r\n");
      out.write("\t\r\n");
      out.write("\t<section class=\"container\">\r\n");
      out.write("\t\t<div class=\"contents\">\r\n");
      out.write("\t\t\t<p class=\"errorTxt\">페이지를 찾을 수 없습니다.</p>\r\n");
      out.write("\t\t\t<div class=\"btnArea btnFixed\">\r\n");
      out.write("\t\t\t\t<div class=\"btnBtm\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" role=\"button\" class=\"btnFloating\">메인으로 가기</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<ul class=\"fLink\">\r\n");
      out.write("\t\t\t<li><a href=\"/home/watwedo/overview.do\" role=\"button\">What We Do</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/home/en/main/main.do\" role=\"button\" title=\"새창열림\">ENGLISH</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/home/contact/contact.do\" role=\"button\">CONTACT</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<div class=\"familySite\">\r\n");
      out.write("\t\t\t<span class=\"frmSelect\">\r\n");
      out.write("\t\t\t\t<select title=\"Family Site\">\r\n");
      out.write("\t\t\t\t\t<option value=\"https://m.ktb.co.kr/kr/MA/main.jsp\">KTB 투자증권</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"http://m.i-ktb.com/static/mobile/html/MA/m_main.html\">KTB 자산운용</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"https://www.ktbst.co.th/index.php?s=p\">KTB ST</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"http://www.ktbpe.co.kr/\">KTB PE</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"http://www.ktbcredit.com/\">KTB 신용정보</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"http://www.ktbvc.com/\">KTB Ventures</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t\t<a href=\"/home/main/main.do\" role=\"button\" class=\"btnMove\">이동</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<p class=\"copyright\">COPYRIGHT&copy;KTB Network. ALL RIGHTS RESERVED</p>\r\n");
      out.write("\t</footer> \r\n");
      out.write(" </body>\r\n");
      out.write("</html>\r\n");
 } else { 
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t<title>에러페이지 - KTB 네트워크</title>\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"/static/home/kr/images/favicon/favicon.ico\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/static/home/kr/css/p_font.css\"> \r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/static/home/kr/css/p_common.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/static/home/kr/css/p_contents.css\">\r\n");
      out.write("\t<!--[if lte IE 8]>\r\n");
      out.write("\t<script src=\"../kr/js/html5shiv.min.js\"></script>\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/static/home/kr/js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/static/home/kr/js/jquery.jscrollpane.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/static/home/kr/js/selectbox.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/static/home/kr/js/common.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"accessbility\"><a href=\"#container\">본문 바로가기</a></div>\r\n");
      out.write("\t<div id=\"wrap\" class=\"wrap\">\r\n");
      out.write("\t\t<header id=\"header\" class=\"header\">\r\n");
      out.write("\t\t\t<div class=\"headArea\"><!-- 열기 open -->\r\n");
      out.write("\t\t\t\t<h1 class=\"logo\"><a href=\"/home/main/main.do\">KTB 네트워크</a></h1>\r\n");
      out.write("\t\t\t\t<a href=\"/home/en/main/main.do\" class=\"engBtn\">ENG</a>\r\n");
      out.write("\t\t\t\t<div class=\"allMenu\">\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<ul class=\"inner\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/home/watwedo/overview.do\">What We Do</a></li><!-- a클릭 시 class=\"on\" 추가 -->\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/home/whoweare/korea.do\">Who We Are</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/home/meetourpartners/all.do\">Meet Our Partners</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/home/news/news/list.do\">News</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/home/contact/contact.do\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/home/about/about.do\">About KTB Group</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<section id=\"container\" class=\"container\">\t\t\t\r\n");
      out.write("\t\t\t<article class=\"content\">\r\n");
      out.write("\t\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t\t<div class=\"errorPage\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"errorTxt\">페이지를 찾을 수 없습니다.<span class=\"sTxt\">서비스 이용에 불편을 드려 대단히 죄송합니다.</span></p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/home/main/main.do\" role=\"button\" class=\"btnXL action\">메인으로 가기</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</article>\t\t\t\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<footer id=\"footer\" class=\"footer\">\r\n");
      out.write("\t\t\t<div class=\"footArea\">\r\n");
      out.write("\t\t\t\t<div class=\"policyList\">\r\n");
      out.write("\t\t\t\t\t<address>\r\n");
      out.write("\t\t\t\t\t\t<span>고객상담 02-788-8400</span>\r\n");
      out.write("\t\t\t\t\t\t<span>팩스 02-788-8597</span>\r\n");
      out.write("\t\t\t\t\t\t<span>이메일 <a href=\"mailto: webmaster@ktbnetwork.com\"> webmaster@ktbnetwork.com</a></span><br>\r\n");
      out.write("\t\t\t\t\t\t<span>Seoul [463-400] 경기도 성남시 분당구 대왕판교로 670(삼평동 682) 유스페이스 2A동 10층</span>\r\n");
      out.write("\t\t\t\t\t</address>\r\n");
      out.write("\t\t\t\t\t<p class=\"copyRight\">COPYRIGHT&copy;KTB Network. ALL RIGHTS RESERVED.</p>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"familySite\">\r\n");
      out.write("\t\t\t\t\t<span class=\"frmSelect\">\r\n");
      out.write("\t\t\t\t\t\t<select title=\"Family Site\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"https://www.ktb.co.kr/top.jsp\">KTB 투자증권</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"http://www.i-ktb.com/\">KTB 자산운용</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"https://www.ktbst.co.th/index.php?s=p\">KTB ST</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"http://www.ktbpe.co.kr/\">KTB PE</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"http://www.ktbcredit.com/\">KTB 신용정보</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"http://www.ktbvc.com/\">KTB Ventures</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"logo\"><img src=\"/static/home/kr/images/common/logo_footer.png\" alt=\"KTB 네트워크\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
 }
} 
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
