/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.39
 * Generated at: 2019-05-09 01:01:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.mobile.kr.general.meetourpartners.overseas;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class overseas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/jsp/common/import/taglib.jspf", Long.valueOf(1555304080000L));
    _jspx_dependants.put("jar:file:/home/ktbnetwork/www/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/home/ktbnetwork/www/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1528432326000L));
    _jspx_dependants.put("jar:file:/home/ktbnetwork/www/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"container\">\r\n");
      out.write("\t\t<div class=\"contents\">\r\n");
      out.write("\t\t\t<div class=\"visualArea\">\r\n");
      out.write("\t\t\t\t<h1 class=\"pageTit\">Meet Our Partners</h1>\r\n");
      out.write("\t\t\t\t<p role=\"text\" class=\"pageTxt\">가장 든든한 투자파트너가 되겠습니다.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"partner\">\r\n");
      out.write("\t\t\t\t<div class=\"tabType1\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/home/meetourpartners/all.do\">ALL</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/home/meetourpartners/domestic.do\">DOMESTIC</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"/home/meetourpartners/overseas.do\"><a href=\"#\" aria-selected=\"true\">OVERSEAS</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"tabCont\"  style=\"display:block\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"hidden\">OVERSEAS</h2>\r\n");
      out.write("\t\t\t\t\t<ul class=\"partnerList\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop32\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_32.gif\" alt=\"B2LINK 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>B2LINK</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop33\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_33.gif\" alt=\"한국엔에프씨 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>BRAVOWHALE TECHNOLOGY</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop34\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_34.gif\" alt=\"B2LINK 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>CHINA CORD BLOOD</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop35\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_35.gif\" alt=\"CORENTEC 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>CORENTEC</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop39\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_39.gif\" alt=\"HOLMES HOLDING CO.LTD. 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>HOLMES HOLDING CO.LTD.</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop41\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_41.gif\" alt=\"IZENE TECH INC. 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>IZENE TECH INC.</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop43\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_43.gif\" alt=\"LOHO HOLDINGS INC. 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>LOHO HOLDINGS INC.</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop44\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_44.gif\" alt=\"MINDRAY MEDICAL 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>MINDRAY MEDICAL</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop47\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_47.gif\" alt=\"UTAN 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>UTAN</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop48\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_48.gif\" alt=\"VERSILICON HOLDINGS 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>VERISILICON HOLDINGS</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop55\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_55.gif\" alt=\"CARSGEN 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>CARSGEN</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop61\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_61.gif\" alt=\"FOCUS MEDIA 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>FOCUS MEDIA</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop72\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_72.gif\" alt=\"ORIG3N 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>ORIG3N</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop73\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_73.gif\" alt=\"ORTHOSENSOR 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>ORTHOSENSOR</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop77\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_77.gif\" alt=\"QEEXO 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>QEEXO</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop80\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_80.gif\" alt=\"SMI 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>SMI</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop81\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_81.gif\" alt=\"TAL EDUCATION GROUP 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>TAL EDUCATION GROUP</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop83\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_83.gif\" alt=\"TUDOU 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>TUDOU</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop87\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_87.gif\" alt=\"XW Labs 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>XW LABS</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop88\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_88.gif\" alt=\"Aprinoia 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>APRINOIA</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop89\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_90.gif\" alt=\"KINOVA 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>KINOVA</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop90\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_89.gif\" alt=\"Berkeleylights 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>BERKELEYLIGHTS</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop92\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_92.gif\" alt=\"Neuroptika 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>NEUROPTIKA</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- 0503 추가 -->\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop100\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_100.gif\" alt=\"Grab 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>Grab</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop101\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_101.gif\" alt=\"Nobroker 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>Nobroker</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#partnerpop102\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/static/mobile/kr/images/contents/img_partners_102.gif\" alt=\"Missfresh 로고 이미지\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>Missfresh</em>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<!-- //0503 추가 -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul><!-- //partnerList -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div><!-- //contents -->\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("<!-- partner소개 레이어팝업(L) -->\r\n");
      out.write("\t<!-- B2LINK -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop32\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">B2LINK</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_32.gif\" alt=\"B2LINK 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.b2link.co.kr\" target=\"_blank\" title=\"새창열기\">http://www.b2link.co.kr</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tB2LiNK는 글로벌 전자상거래 기업으로, 국내 뷰티 &amp; 패션 상품을 중국 및 동남아시아 이커머스 채널에 유통해 주고 있으며 중국인 대상 자체 모바일 커머스 운영, 빅데이터 비즈니스를 통해 유통 채널의 혁신을 이루어 가고 있습니다.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //B2LINK -->\r\n");
      out.write("\t<!-- BRAVOWHALE TECHNOLOGY -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop33\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">BRAVOWHALE TECHNOLOGY</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_33.gif\" alt=\"BRAVOWHALE TECHNOLOGY 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.bravowhale.com\" target=\"_blank\" title=\"새창열기\">http://www.bravowhale.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tBravo Whale Technology는 2014 년에 설립되었으며, 시스템 소프트웨어 개발업체입니다. 클라우드 및 모바일을 기반으로 자산관리 업체들에게 맞춤형 관리 시스템 소프트웨어를 제공하고 있습니다. 현재 북경 및 상해에 사무소를 설립하였으며, 쿤산에 R&D센터를 구축하였습니다. \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //BRAVOWHALE TECHNOLOGY -->\r\n");
      out.write("\t<!-- CHINA CORD BLOOD -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop34\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">CHINA CORD BLOOD</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_34.gif\" alt=\"CHINA CORD BLOOD 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.chinacordbloodcorp.com\" target=\"_blank\" title=\"새창열기\">http://www.chinacordbloodcorp.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tChina Cord Blood(CCBC)는 생명 과학 연구 분야의 급속한 발전, 인구의 증가 및 줄기 세포를 이용한 임상 응용 분야의 빠른 발달에 힘입어 제대혈 줄기 세포의 저장 서비스를 제공하는 데 주력하는 생명 과학 기업입니다.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //CHINA CORD BLOOD -->\r\n");
      out.write("\t<!-- CORENTEC -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop35\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">CORENTEC</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_35.gif\" alt=\"CORENTEC 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.corentec.com\" target=\"_blank\" title=\"새창열기\">http://www.corentec.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tCorentec의 중앙 기술 연구소(Central Technology Institute)는 환자들이 발달된 의료 기기와 수술 기술을 통해 더 나은 삶의 질을 누릴 수 있도록 돕기 위해 설립되었습니다.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //CORENTEC -->\r\n");
      out.write("\t<!-- HOLMES HOLDING CO.LTD. -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop39\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">HOLMES HOLDING CO.LTD.</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_39.gif\" alt=\"HOLMES HOLDING CO.LTD. 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.mogoroom.com\" target=\"_blank\" title=\"새창열기\">http://www.mogoroom.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t2013년 12월에 설립된 Holmes Holding 주식회사(Mogo Room)는 사무직 종사자들의 장기 임대 수요에 대응하여 고품질의 서비스를 제공함에 따라 중국의 선도적인 공동 아파트 시설 기업으로 거듭났습니다. \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //HOLMES HOLDING CO.LTD. -->\r\n");
      out.write("\t<!-- IZENE TECH INC. -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop41\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">IZENE TECH INC.</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_41.gif\" alt=\"IZENE TECH INC. 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.b5m.com\" target=\"_blank\" title=\"새창열기\">http://www.b5m.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tB5M은 전체 네트워크 서비스에 원스톱 쇼핑 플랫폼과 무료 배송 서비스를 제공하며 구매자들이 고품질의 상품들을 가장 경제적으로 구매할 수 있도록 도와줍니다. \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //IZENE TECH INC. -->\r\n");
      out.write("\t<!-- LOHO HOLDINGS INC. -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop43\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">LOHO HOLDINGS INC.</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_43.gif\" alt=\"LOHO HOLDINGS INC. 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.loho88.cn\" target=\"_blank\" title=\"새창열기\">http://www.loho88.cn</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tLOHO는 안경 디자인, 생산, 판매 및 서비스를 제공하고 있습니다.중국 전국에 매장이 분포되어 있으며, 온오프라인 형식으로 판매하고 있습니다.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //LOHO HOLDINGS INC. -->\r\n");
      out.write("\t<!-- MINDRAY MEDICAL -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop44\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">MINDRAY MEDICAL</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_44.gif\" alt=\"LOHO HOLDINGS INC. 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.mindray.com\" target=\"_blank\" title=\"새창열기\">http://www.mindray.com </a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tMindray Medical는 1991년 중국 심천에서 설립한 세계 선두의 의료 H/W 및 S/W 제공상입니다.현재 31개 나라에서 41개 자회사 보유하고 있고 글로벌 R&amp;D, 영업, 서비스네트워크 형성되었습니다.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //MINDRAY MEDICAL -->\r\n");
      out.write("\t<!-- UTAN -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop47\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">UTAN</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_47.gif\" alt=\"UTAN 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.yurongcorp.com\" target=\"_blank\" title=\"새창열기\">http://www.yurongcorp.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tUtan는 여성 전문 SNS &amp; E-commerce 제공상입니다. 운영중인 V-Line Fitness, Girl's Alliance등 5개 APP를 통해 6000만명의 유저수를 보유하고 있습니다.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //UTAN -->\r\n");
      out.write("\t<!-- VERSILICON HOLDINGS -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop48\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">VERISILICON HOLDINGS</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_48.gif\" alt=\"VERSILICON HOLDINGS 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.verisilicon.com\" target=\"_blank\" title=\"새창열기\">http://www.verisilicon.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tVeriSilicon Holdings 주식회사는 모바일 인터넷 장치, 데이터센터, 사물 인터넷(Internet of Things, IoT), 웨어러블 전자기기, 스마트 홈 및 자동차 등 다양한 최종 시장에서 폭 넓은 용도로 사용 가능한 IP 중심적인 플랫폼 기반 맞춤형 실리콘 솔루션과 말단간 전도체 턴키 서비스를 제공하는 서비스로서의 실리콘 플랫폼(Silicon Platform as a Service, SiPaaS™) 기업입니다. \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //VERSILICON HOLDINGS -->\r\n");
      out.write("\t<!-- CARSGEN -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop55\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">CARSGEN</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_55.gif\" alt=\"CARSGEN 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.carsgen.com \" target=\"_blank\" title=\"새창열기\">http://www.carsgen.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tCARsgen Therapeutics는 혁신적인 면역항암제인 CAR-T를 개발하여 난치성 암 치료제를 개발하고자 합니다.<br>CARsgen은 중국뿐만 아니라 Global에서 First in Class 고형암 치료용 CAR-T를 개발 중이며, 인류가 암을 극복하는데 앞장서고자 합니다.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //CARSGEN -->\r\n");
      out.write("\t<!-- FOCUS MEDIA -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop61\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">FOCUS MEDIA</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_61.gif\" alt=\"FOCUS MEDIA 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.focusmedia.cn\" target=\"_blank\" title=\"새창열기\">http://www.focusmedia.cn</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t포커스미디어는 엘리베이터 LCD광고로 유명세를 떨친 중국 최대의 옥외광고 회사입니다. 2005년 나스닥에 성공적으로 상장하며 중국 미디어업계에서 상장 신화를 만들어낸 기업입니다. \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //FOCUS MEDIA -->\r\n");
      out.write("\t<!-- ORIG3N -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop72\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">ORIG3N</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_72.gif\" alt=\"ORIG3N 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.orig3n.com\" target=\"_blank\" title=\"새창열기\">http://www.orig3n.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tORIG3N은 2012년 노벨상을 받은 기술인 역분화유도만능줄기세포(iPS) 기술을 이용하여, iPS Banking 서비스 및 iPS based 세포 실험모델 제공을 하는 기업입니다. 현재 전세계에서 가장 많은 Human iPS 샘플을 Crowd Sourcing 형태로 확보 하였고, 희귀병 iPS 샘플 등을 만들어 희귀병의 신약개발에도 도움을 주고 있습니다.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //ORIG3N -->\r\n");
      out.write("\t<!-- ORTHOSENSOR -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop73\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">ORTHOSENSOR</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_73.gif\" alt=\"ORTHOSENSOR 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.orthosensor.com\" target=\"_blank\" title=\"새창열기\">http://www.orthosensor.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tOrthosensor는 스마트 인공관절 수술을 위한 제품을 개발하는 회사 입니다. Orthosensor가 개발한 인공관절 삽입 수술시 스마트센서를 이용하여 인공관절의 체내에 최적의 상태로 삽입되는 압력을 정량화 하여 보여주어 재수술 및 후유증을 최소화 하고 있습니다. 나아가 체내 삽입형 센서를 개발해 수술후 환자를 실시간 monitoring 하며 쌓인 Data를 이용해 인공관절 수술 환자들의 삶의 질을 높이고자 합니다.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //ORTHOSENSOR -->\r\n");
      out.write("\t<!-- QEEXO -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop77\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">QEEXO</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_77.gif\" alt=\"QEEXO 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.qeexo.com\" target=\"_blank\" title=\"새창열기\">http://www.qeexo.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tQeexo는 HCI (인간과 컴퓨터의 상호 작용)와 머신러닝 기술을 기반으로하여 사용자와 모바일 기기 및 터치 기기가 상호 작용하는 방식을 혁신하는 UI 플랫폼을 제공하고 있습니다. \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //QEEXO -->\r\n");
      out.write("\t<!-- SMI -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop80\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">SMI<em>HKSE</em></h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit type02\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_80.gif\" alt=\"SMI 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.smi198.com\" target=\"_blank\" title=\"새창열기\">http://www.smi198.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tSMI Holdings는 엔터테인먼트 관련 업체로 주요 사업은 영화관 운영, 영화/드라마 제작 및 배급, 광고, 온라인 쇼핑몰 운영 들이 있습니다. \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //SMI -->\r\n");
      out.write("\t<!-- TAL EDUCATION GROUP -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop81\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">TAL EDUCATION GROUP<em>NYSE</em></h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit type02\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_81.gif\" alt=\"TAL EDUCATION GROUP 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.100tal.com\" target=\"_blank\" title=\"새창열기\">http://www.100tal.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t중국의 선도적인 교육 기술 회사 중 하나로 아이들을 위한 더 나은 학습 경험을 제공하며 인터넷 기술과 교육의 통합을 촉진하기 위해 최선을 다하고 있는 기업입니다.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //TAL EDUCATION GROUP -->\r\n");
      out.write("\t<!-- TUDOU -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop83\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">TUDOU<em>NYSE</em></h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit type02\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_83.gif\" alt=\"TUDOU 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.tudou.com\" target=\"_blank\" title=\"새창열기\">http://www.tudou.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tTudou는 중국 온라인 동영상 전문 사이트로 2012년 경쟁사 Youku와 합병하였습니다. 이후 중국 최대의 인터넷 전자상거래 기업 알리바바로부터 투자를 받았으며, 현재 중국 판 유투브라 불리며 중국 최대의 동영상 플랫폼으로 성장하였습니다.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //TUDOU -->\r\n");
      out.write("\t<!-- XW Labs -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop87\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">XW LABS</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_87.gif\" alt=\"XW Labs 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.xwlabs.com\" target=\"_blank\" title=\"새창열기\">http://www.xwlabs.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tXW Laboratories 는 중국 우한에 위치한 중추신경계(Central Nerve System, CNS) 전문 신약 개발 기업입니다.<br>당사를 비롯하여 global 제약사인 Johnson &amp; Johnson, global CRO 인 WuXi, 그리고 Asia Pacific 지역의 Top tier 투자자인 KPCB China, WI Harper, 그리고 Element Capital 에게서 투자를 유치 하였습니다.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //XW Labs -->\r\n");
      out.write("\t<!-- APRINOIA -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop88\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">APRINOIA</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_88.gif\" alt=\"APRINOIA 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"https://www.aprinoia.com\" target=\"_blank\" title=\"새창열기\">https://www.aprinoia.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tAprinoia는 퇴행성 뇌질환 전문 바이오텍입니다. 알츠하이머성 치매, 파킨슨 병 등 다양한 퇴행성 뇌질환의 정확한 진단을 위한 PET Tracer와 치료제(저분자 화합물, 항체)를 개발하고 있습니다.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //APRINOIA -->\r\n");
      out.write("\t<!-- KINOVA -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop89\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">KINOVA</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_90.gif\" alt=\"KINOVA 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"https://www.kinovarobotics.com/en\" target=\"_blank\" title=\"새창열기\">https://www.kinovarobotics.com/en</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tKinova는 캐나다 소재의 글로벌 서비스로봇암 제작업체입니다. 거동이 불편한 장애인 및 노인의 활동을 지원하는 서비스로봇 분야에서 시작하여, 실생활의 여러 활동에 높은 자유도를 지원하는 기술을 개발하고 있습니다.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //KINOVA -->\r\n");
      out.write("\t<!-- BERKELEYLIGHTS -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop90\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">BERKELEYLIGHTS</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_89.gif\" alt=\"BERKELEYLIGHTS 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"https://www.berkeleylights.com\" target=\"_blank\" title=\"새창열기\">https://www.berkeleylights.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tBerkeley Lights는 연구 및 신약개발에 사용되는 세포연구장비 제작업체입니다. Opto Eletro Positioning(전기장을 이용한 세포제어 기술)을 기반으로 세포의 분리, 배양, 분석 및 추출 과정에 있어 시간과 비용을 획기적으로 절감할 수 있으며, 세포주개발과 항체개발 등 다양한 분야에 활용가능한 제품을 개발하고 있습니다.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //BERKELEYLIGHTS -->\r\n");
      out.write("\t<!-- NEUROPTIKA -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop92\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">NEUROPTIKA</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_92.gif\" alt=\"NEUROPTIKA 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"https://www.neuroptika.com\" target=\"_blank\" title=\"새창열기\">https://www.neuroptika.com</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tNeuoptika는 시신경 재생 신약 및 치료제 개발업체입니다. 신경세포의 재생을 통한 각막 손상복구와 안구건조증 개선을 비롯하여 라식후 안구건조증, 녹내장 및 기타 시신경 관련 희귀질환 개선에 확대 가능한 치료제를 개발중입니다.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //NEUROPTIKA -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 0503 추가 -->\r\n");
      out.write("\t<!-- Grab -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop100\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">Grab</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_100.gif\" alt=\"Grab 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"https://www.grab.com/sg/\" target=\"_blank\" title=\"새창열기\">https://www.grab.com/sg/</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t싱가포르에 본부를 둔 동남아시아 최대 차량공유 업체입니다. 그랩은 &apos;승차 공유&apos; 시장에만 머무르지 않고 음식 배달 서비스 &apos;그랩푸드&apos;, 물류 배달 서비스 &apos;그랩 익스프레스&apos;, 모바일 결제 시스템 &apos;그랩 페이&apos; 등 모든 일상생활을 지배하는 슈퍼 애플리케이션(앱)으로 진화하는 중입니다.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //Grab -->\r\n");
      out.write("\t<!-- Nobroker -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop101\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">Nobroker</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_101.gif\" alt=\"Nobroker 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"https://www.nobroker.in/\" target=\"_blank\" title=\"새창열기\">https://www.nobroker.in/</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tNoBroker 는 인도 기반의 부동산 관련 스타트업으로 기존의 off-line 부동산 중개인을 배제하고 웹과 모바일, 그리고 자체 콜센터를 통해 임대인과 임차인이 직접 연결될 수 있도록 하는 부동산 개인간(P2P) 직거래 플랫폼을 구축하여 서비스 중입니다.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //Nobroker -->\r\n");
      out.write("\t<!-- Missfresh -->\r\n");
      out.write("\t<div class=\"layerPop\" id=\"partnerpop102\">\r\n");
      out.write("\t\t<div class=\"layerContainer\">\r\n");
      out.write("\t\t\t<h2 class=\"layerTit\">Missfresh</h2>\r\n");
      out.write("\t\t\t<div class=\"layerCont\" tabindex=\"0\">\r\n");
      out.write("\t\t\t\t<div class=\"contTit\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"><img src=\"/static/mobile/kr/images/contents/img_partners_102.gif\" alt=\"Missfresh 로고 이미지\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"contBtn\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"https://www.missfresh.cn/\" target=\"_blank\" title=\"새창열기\">https://www.missfresh.cn/</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\tXuzheng 과 Zengbin 이 창업한 중국의 온라인 그로서리 회사로, 과일, 달걀, 고기, 생선류, 야채류 등을 온라인으로 판매하고 있습니다.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"layerClose\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //Missfresh -->\r\n");
      out.write("<!-- //0503 추가 -->\r\n");
      out.write("\t\r\n");
      out.write("<!-- //partner소개 레이어팝업(L) -->\r\n");
      out.write("\t<div class=\"dimmed\"></div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
