/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.39
 * Generated at: 2020-05-11 04:17:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.home.kr.general.main.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/jsp/common/import/taglib.jspf", Long.valueOf(1555304080000L));
    _jspx_dependants.put("jar:file:/home/ktbnetwork/www/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/home/ktbnetwork/www/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1528432326000L));
    _jspx_dependants.put("jar:file:/home/ktbnetwork/www/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\r\n");
      out.write("\t\t<section id=\"container\" class=\"container\">\r\n");
      out.write("\t\t\t<h1 class=\"hidden\">네트워크 메인</h1>\r\n");
      out.write("\t\t\t<article class=\"content\">\r\n");
      out.write("\t\t\t\t<div class=\"sectionWrap\" style=\"\">\r\n");
      out.write("\t\t\t\t\t<!-- section1 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"section1\" style=\"height:850px\"><!-- 각 섹션은 브라우저 높이값 - header 높이 -80px 을 height로 설정 -->\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"hidden\">회사소개 메뉴 및 대표상품 안내</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"mainVisual\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"visualWrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"swiper-wrapper\" style=\"width:8400px\"><!-- width값:li전부 더한 값 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"swiper-slide\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"/home/watwedo/overview.do\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"/static/home/kr/images/main/main_visual1.png\" alt=\"내일을 보는 금융 KTB 자산운용은 고객의 내일을 봅니다. 내일을 보는 투자를 통해 성공을 만들어 냅니다. 회사소개 바로가기\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"swiper-slide\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"/static/home/kr/images/main/main_visual2.png\" alt=\"미래를 보는 KTB 성장가능성 있는 신생벤처기업 투자를 통해 미래의 가치를 만들어갑니다. 상품 바로가기\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"swiper-slide\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"/static/home/kr/images/main/main_visual3.png\" alt=\"함께 성장하는 KTB 설립 이후 38년간 IPO를 통해 277개의 기업(우회상장 포함)과 함께 하였습니다. 상품 바로가기\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"swiper-slide\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"/static/home/kr/images/main/main_visual4.png\" alt=\"세계로 향하는 네트워크 수십 년간 축적된 안목과 글로벌 네트워크를 통해 세계로 나아갑니다. 상품 바로가기\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"paging\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"rolling_btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btnPrev\"><span>prev</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btnStop\"><span>stop</span></a><!-- 정지 버튼 눌러서 멈출 경우 <a href=\"#\" class=\"btnPlay\"><span>play</span></a> 로 변경 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!--<a href=\"#\" class=\"btnPlay\"><span>play</span></a>-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btnNext\"><span>next</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"pageNum\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong class=\"now\">02</strong>\t/ 05\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<article class=\"newsArea\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"newsWrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>NEWS</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"newsBtn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"before\">이전 뉴스 보기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"next\">다음 뉴스 보기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul><!-- 요건 1: 버튼 클릭 시 li margin-top 값 조절되어 상하 롤링 ,요건2 : a 태그 공백 포함 50자 말줄임처리 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"/home/news/news/view.do?num=1\">제 11기 결산공고</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"/home/news/news/view.do?num=2\">액면분할에 따른 구주권 제출 및 채권자 이의 제출 공고</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"/home/news/news/view.do?num=3\">외부감사인 선임 공고</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</article><!-- //newsArea -->\r\n");
      out.write("\t\t\t\t\t\t<em class=\"scrollDown\"><span class=\"hidden\">scroll down</span></em>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- //section1 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- section2 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"section2\" style=\"height:770px\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"sTit\">펀드 현황을 확인하세요.<em>KTB네트워크의 성장과 함께 하세요.</em></h3>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"tabArea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#tab01\" aria-selected=\"true\" class=\"on\" style=\"font-size: 18px;\">청산펀드 현황</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#tab02\" style=\"font-size: 18px;\">운용펀드 현황</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tabCon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 청산펀드 현황 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"tab01\" class=\"list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"hidden\">청산펀드 현황</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt class=\"name\">펀드수</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd class=\"num\">53</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt class=\"name\">납입총액<span>(단위 : 억원)</span></dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd class=\"num\">12,742</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt class=\"name\">분배총액<span>(단위 : 억원)</span></dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd class=\"num\">19,700</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt class=\"name\">IRR<span>(단위 : %)</span></dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd class=\"num\">19.75</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"tooltip\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<em>작성기준</em>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"tipOpen\"><span>도움말</span></a><!-- 클릭 시 class=\"on\" 추가 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"msg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong class=\"tit\">작성기준</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"txt\">- 2019.12.31 현재</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"txt\">- 2000.01.01 이후 청산한 퍼드 기준</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"txt\">- IRR: 성과보수 포함, 납입금액 가중평균 수익률</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btnClose on\"><span>닫기</span></a><!-- 클릭 시 <a class=\"tipOpen on\"> 의 class=\"on\" 삭제 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- //청산펀드 현황 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 운용펀드 현황 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"tab02\" class=\"list\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"hidden\">운용펀드 현황</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt class=\"name\">펀드수</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd class=\"num\">17</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt class=\"name\">약정총액<span>(단위 : 억원)</span></dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd class=\"num\">8,835</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt class=\"name\">투자기업수</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd class=\"num\">297</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dt class=\"name\">투자총액<span>(단위 : 억원)</span></dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<dd class=\"num\">6,807</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"tooltip\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<em>작성기준</em>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"tipOpen\"><span>도움말</span></a><!-- 클릭 시 class=\"on\" 추가 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"msg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong class=\"tit\">작성기준</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"txt\">- 2019.12.31 현재</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btnClose on\"><span>닫기</span></a><!-- 클릭 시 <a class=\"tipOpen on\"> 의 class=\"on\" 삭제 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- //운용펀드 현황 -->\r\n");
      out.write("\t\t\t\t\t\t\t</div><!-- //tabCon -->\r\n");
      out.write("\t\t\t\t\t\t</div><!-- //fundProduct -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- //section2 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- section3 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"section3\" style=\"height:850px\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"sTit\">운용철학을 소개합니다.<em>장기적이고 안정적인 운용성과를 추구합니다.</em></h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"imgArea\"><img src=\"/static/home/kr/images/main/img_goal.png\" alt=\"Compliance, Active Value Creation, Alignment of Interest\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"conArea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>운용철학</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/home/watwedo/philosophy.do\" class=\"moreBtn\">자세히보기</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><strong>Alignment of Interest</strong>펀드 참여자 간의 이해관계 일치를 통한 공동의 목표 부여</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><strong>Active Value Creation</strong>투자업체 지원 및 가치창출 활동을 통해 지속 가능한 성장도모, <br>투자업체 성공과 목표수익 달성</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><strong>Compliance</strong>Compliance 체계 및 점검활동 통한 펀드 운용위험 통제, <br>Moral Hazard 예방</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- //section3 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"etcArea\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"member\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>성공적인 투자를 위해 <br>KTB네트워크의 구성원들이<br>함께 합니다.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/home/whoweare/korea.do\">Who We Are</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"partners\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><strong>Meet Our Partners</strong>가장 든든한 투자파트너가 되겠습니다.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/home/meetourpartners/all.do\" class=\"moreBtn\">자세히보기</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div><!-- //sectionWrap -->\r\n");
      out.write("\t\t\t</article><!-- //content -->\r\n");
      out.write("\t\t</section>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
