/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.39
 * Generated at: 2019-04-17 17:46:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.home.kr.general.news.news;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _1018_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/jsp/common/import/taglib.jspf", Long.valueOf(1555304080000L));
    _jspx_dependants.put("jar:file:/home/ktbnetwork/www/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/home/ktbnetwork/www/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1528432326000L));
    _jspx_dependants.put("jar:file:/home/ktbnetwork/www/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<section id=\"container\" class=\"container\">\r\n");
      out.write("\t\t\t<nav class=\"nav\">\r\n");
      out.write("\t\t\t\t<ol class=\"navArea\"><li>HOME</li><li>News</li></ol>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t<div class=\"visualArea\">\r\n");
      out.write("\t\t\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t\t\t<h1 class=\"pageTit\">News</h1>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"pageTxt\">KTB네트워크의 공지사항을 안내해드립니다.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t\t<div class=\"boardView\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"viewTit\">\r\n");
      out.write("\t\t\t\t\t\t\t<strong class=\"tit\">케이티비네트워크 상반기 가결산 공시</strong>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"con\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"date\">2011.01.24</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"viewFile\"><a href=\"/doc/Notic201011.doc\">케이티비네트워크 상반기 가결산 공시.doc</a></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"viewCon\">\r\n");
      out.write("\t\t\t\t\t\t\t본 자료는 ‘여신전문금융업감독규정’ 제23조 규정에 따라 작성된 것입니다.\r\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"titDep3\">1. 영업규모</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"tright\">금액(단위:원)</p>\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"tblH\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<caption>케이티비네트워크 상반기 가결산 공시 구분 값에 따른 금액(백만원), 부문별 비중</caption>\r\n");
      out.write("\t\t\t\t\t\t\t\t<colgroup><col style=\"width:34%\"><col style=\"width:33%\" span=\"2\"></colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">구분</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">금액(백만원)</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">부문별 비중</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"row\" class=\"tleft\">영업수익 계</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"tright\">8,576</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"tright\">100%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"row\" class=\"tleft\">가.이자수익</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"tright\">599</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"tright\">7%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"row\" class=\"tleft\">나.유가증권평가및처분이익</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"tright\">1,638</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"tright\">19%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"row\" class=\"tleft\">다.신기술금융대출금평가및처분이익</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"tright\">199</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"tright\">2%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"row\" class=\"tleft\">라.지분법이익</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"tright\">3,448</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"tright\">40%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"row\" class=\"tleft\">마.수수료수익</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"tright\">2,623</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"tright\">31%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"row\" class=\"tleft\">바.기타영업수익</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"tright\">69</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"tright\">1%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"mtS\">1)케이티비네트워크(舊케이티비캐피탈)은 모회사인 케이티비투자증권이 증권업인가를 받으면서, 증권거래 법 등 금융관련법상 겸업금지원칙에 따라 기존의 신기술사업금융업자 유관(시설대여업 포함)업무를 물적분할하여 분할 자회사로 이전함에 따라 신설된 신설분할 법인임.</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"mtS\">2)분할회사의 특성에 맞는 경영계획 수립과 경영자원의 효율적 배분을 통해 기존 자산관리의 효율성을 극대화하여, 투자조합 출자자 등에 대한 선관의무 이행에 만전을 기하는 것을 목표로 함.</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"mtS\">3)신기술금융부문의 경우 당사는 前身인 케이티비네트워크로 거슬러 올라가면, 1981년 설립이래 벤처투자의 선도업체(First Mover)로서 국내 벤처산업의 육성에 이바지해 왔으며, 축적된 투자 노하우와 시스템을 바탕으로 현재까지도 국내 벤처투자를 주도하여 옴. 2005년 이후에는 업종에 있어서 첨단산업 분야뿐만 아니라 전통제조업, 유통, 서비스, 제약 등으로, 투자지역에 있어서는 중국, 베트남, 필리핀, 일본 등으로 투자대상과 투자지역의 다각화도 적극적으로 추진하여 투자 리스크 분산을 통한 안정적 수익 창출을 도모하고 있슴. 2010년09월 현재 총 16개 조합에 1,239억원의 투자잔액을 기록하고 있음.</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"mtS\">4)또한1999년 「산업발전법」의 시행과 더불어 기업구조조정전문회사로 등록한 이래, 총20개의 기업구조조정펀드를 결성?운용하여 왔으며, CRC펀드의 경우2010년 9월 현재 총 3개조합에 76억원의 투자잔액을 기록하고 있음.</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"titDep3\">2.주요 경영지표 – 첨부 파일을 참조하여 주세요</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"titDep3\">3.요약 재무제표 – 첨부 파일을 참조하여 주세요</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<ul class=\"baordIndex\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/home/news/news/view.do?page=");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("&num=19\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"arrow next\">다음글</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tit\">상호 및 공고방법 변경</div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/home/news/news/view.do?page=");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("&num=17\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"arrow prev\">이전글</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tit\">채권자 이의제출 공고</div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<div class=\"btnArea\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/home/news/news/list.do?page=");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write("\" role=\"button\" class=\"btnXL\">목록보기</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/jsp/home/kr/general/news/news/1018.jsp(93,45) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.page}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /WEB-INF/jsp/home/kr/general/news/news/1018.jsp(99,45) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.page}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent(null);
      // /WEB-INF/jsp/home/kr/general/news/news/1018.jsp(106,44) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.page}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }
}
